# Generated by Django 3.2.8 on 2021-11-03 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('comment', models.CharField(max_length=2000)),
                ('evaluation', models.IntegerField()),
                ('match_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_summoner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='user.summoner')),
                ('reported_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporting', to='user.summoner')),
            ],
        ),
    ]
