# Generated by Django 3.2.8 on 2021-11-25 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0004_apology"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apology",
            name="report",
        ),
        migrations.AddField(
            model_name="report",
            name="apology",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="report.apology",
            ),
        ),
    ]
