# Generated by Django 3.2.8 on 2021-11-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0005_auto_20211125_0214"),
    ]

    operations = [
        migrations.AddField(
            model_name="apology",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
