version: "3.1"

services:
  backend_container:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
    ports:
      - "8000:8000"
    env_file:
      - .secrets/base.json
    working_dir: /app
    command:
      - /bin/bash
      - cd backend
      - cd gaejosim
      - python manage.py makemigrations
      - python manage.py migrate
      - python manage.py runserver 0.0.0.0:8000

  mysql:
    image: mysql:8
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3306:3306"

