# Generated by Django 3.2.8 on 2021-11-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='summoner_puuid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='summoner_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
