# Generated by Django 3.2.8 on 2021-11-03 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MannerPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", models.IntegerField(default=80)),
                ("tag1", models.IntegerField(default=5)),
                ("tag2", models.IntegerField(default=5)),
                ("tag3", models.IntegerField(default=5)),
                ("tag4", models.IntegerField(default=5)),
                ("tag5", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="summoner",
            name="manner_point",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.mannerpoint",
            ),
        ),
    ]
