# Generated by Django 3.2.8 on 2021-11-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20211103_1540"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summoner",
            name="manner_point",
        ),
        migrations.DeleteModel(
            name="MannerPoint",
        ),
    ]
