# Generated by Django 3.2.8 on 2021-11-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211103_1226'),
        ('user', '0004_auto_20211103_1543'),
    ]

    operations = [
    ]
