# Generated by Django 3.2.8 on 2021-11-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_summoner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mannerpoint',
            name='tag1',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='mannerpoint',
            name='tag2',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='mannerpoint',
            name='tag3',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='mannerpoint',
            name='tag4',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='mannerpoint',
            name='tag5',
            field=models.FloatField(default=5),
        ),
    ]
